In [104]:
import pandas as pd

In [105]:
data = pd.read_csv('data/ingredients.csv', sep=',')
display(data)

,id,name,packing,store,price,type
0,1,сахар,1 кг,лента,62.99,продукты
1,2,печенье на декор,1 упаковка,лента,89.99,декор
2,3,сгущенка рогачев,370 мл,лента,164.99,продукты
3,4,малина и голубика в сердце,1 упаковка,перекресток,579.99,декор
4,5,яйцо с1 окское,10 шт,лента,109.99,продукты
...,...,...,...,...,...,...
133,134,глазурь темная,1 кг,ольга,560.00,декор
134,135,трайфлы,100 шт,ольга,1200.00,упаковка
135,136,коробка кап6,1 шт,ольга,60.00,упаковка
136,137,яйцо с0 365 дней,10 штук,лента,99.99,продукты
137,138,малина с/м,1 кг,ольга,1600.00,продукты

In [106]:
data[data['type'] =='продукты']['packing'].value_counts()

packing
1 кг          18
80 г           8
370 мл         8
300 г          6
1 л            6
2 кг           4
10 штук        4
5 л            3
10 шт          3
500 мл         3
260 мл         2
220 г          2
500 г          2
580 мл         2
50 г           2
850 мл         2
10 г           2
350 г          1
10 кг          1
450 г          1
2 г            1
425 мл         1
100 г          1
75 г           1
150 г          1
180 г          1
1,5 г          1
30 шт          1
0.5 л          1
200 мл         1
1 упаковка     1
2,2 кг         1
Name: count, dtype: int64

>Задача №1: получить столбец с ценой за 100г/100мл ингридиента
Для этого: 
* для упаковки "_ кг" привести к цене за 100 г 
* для упаковки "_ л" привести к цене за 100 мл
* для упаковки "_ штук" привести к цене за 1 штуку
* для упаковки "1 упаковка" оставить как есть
* для упаковки "_ кг" привести к цене за 100 г

In [107]:
def to_gramm(string):
    string = string.split(' ')

    if string[1] == 'кг':
        if ',' in string[0]:
            return float(string[0].replace(',','.')) * 1000
        else:
            return float(string[0]) * 1000
    elif string[1] == 'л':
            if ',' in string[0]:
                return float(string[0].replace(',','.')) * 1000
            else:
                return float(string[0]) * 1000
    else:
        if ',' in string[0]:
            return float(string[0].replace(',','.'))
        else:
            return float(string[0])

In [108]:
to_gramm('1 упаковка')

1.0

In [109]:
def units(string):
    string = string.split(' ')

    if string[1] == 'кг' or string[1] == 'г':
        return 'г'
    elif string[1] == 'л' or string[1] == 'мл':
        return 'мл'
    elif string[1] == 'штук' or string[1] == 'шт' or string[1] == 'лист':
        return 'шт'
    elif string[1] == 'упаковка':
        return 'уп'
    else:
        pass

In [110]:
data['Units of measurement'] = data['packing'].apply(units)

In [111]:
data['package weight'] = data['packing'].apply(to_gramm)

In [118]:
data

,id,name,packing,store,price,type,Units of measurement,package weight
0,1,сахар,1 кг,лента,62.99,продукты,г,1000.0
1,2,печенье на декор,1 упаковка,лента,89.99,декор,уп,1.0
2,3,сгущенка рогачев,370 мл,лента,164.99,продукты,мл,370.0
3,4,малина и голубика в сердце,1 упаковка,перекресток,579.99,декор,уп,1.0
4,5,яйцо с1 окское,10 шт,лента,109.99,продукты,шт,10.0
...,...,...,...,...,...,...,...,...
133,134,глазурь темная,1 кг,ольга,560.00,декор,г,1000.0
134,135,трайфлы,100 шт,ольга,1200.00,упаковка,шт,100.0
135,136,коробка кап6,1 шт,ольга,60.00,упаковка,шт,1.0
136,137,яйцо с0 365 дней,10 штук,лента,99.99,продукты,шт,10.0
137,138,малина с/м,1 кг,ольга,1600.00,продукты,г,1000.0

In [133]:
mask1 = (data['Units of measurement'] == 'шт') | (data['Units of measurement'] == 'уп')
mask2 = (data['Units of measurement'] == 'г') | (data['Units of measurement'] == 'мл')

In [136]:
data[mask2]

,id,name,packing,store,price,type,Units of measurement,package weight
0,1,сахар,1 кг,лента,62.99,продукты,г,1000.0
2,3,сгущенка рогачев,370 мл,лента,164.99,продукты,мл,370.0
5,6,мука макфа 2 кг,2 кг,лента,139.99,продукты,г,2000.0
6,7,карамель топпинг,300 г,лента,99.99,продукты,г,300.0
7,8,арахис соленый 50 г,50 г,лента,29.99,продукты,г,50.0
...,...,...,...,...,...,...,...,...
129,130,грецкий орех,1 кг,ольга,900.00,продукты,г,1000.0
130,131,мастика,1 кг,ольга,400.00,декор,г,1000.0
132,133,шоколад темный вес,1 кг,ольга,1550.00,продукты,г,1000.0
133,134,глазурь темная,1 кг,ольга,560.00,декор,г,1000.0
137,138,малина с/м,1 кг,ольга,1600.00,продукты,г,1000.0

In [139]:
data1 = data.copy()

In [141]:

data1[mask1]['price per weight'] = data[mask1]['price'] / data[mask1]['package weight']
data1[mask2]['price per weight'] = (100 / data[mask2]['package weight']) * data[mask2]['price']

C:\Users\PC\AppData\Local\Temp\ipykernel_11220\2563280785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1[mask1]['price per weight'] = data[mask1]['price'] / data[mask1]['package weight']
C:\Users\PC\AppData\Local\Temp\ipykernel_11220\2563280785.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1[mask2]['price per weight'] = (100 / data[mask2]['package weight']) * data[mask2]['price']